#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Systemd services and timers
for suffix in "${systemd_services_suffixes[@]}"; do
    if ynh_exec_warn_less yunohost service status "$app_suffix" >/dev/null; then
        yunohost service remove "$app_suffix"
    fi
    ynh_systemd_action --service_name="$app$suffix.timer" --action="stop"
    ynh_systemd_action --service_name="$app$suffix.timer" --action="disable"
    ynh_remove_systemd_config --service_name="$app$suffix"
    ynh_secure_remove "/etc/systemd/system/$app$suffix.timer"
done

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove sudoers
rm "/etc/sudoers.d/$app"

ynh_secure_remove "/etc/yunohost/hooks.d/backup_method/05-${app}_app"

#=================================================
# REMOVE SSH CONFIG
#=================================================
ynh_script_progression --message="Removing ssh config"

sed -e "/begin ${app}/,/end ${app}/{/.*/d}" /root/.ssh/config -i || true

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
