#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping $app's systemd service..." --weight=1

if grep "${app}.timer" /etc/yunohost/services.yml > /dev/null ; then
    yunohost service remove $app.timer
    ynh_systemd_action --service="$app" --action="stop"
    ynh_systemd_action --service="$app.timer" --action="disable"
fi

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
#ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# old versions did not have delimiters in ~/.ssh/config making removal in
# multi-instance cases break the remaining instances.
# So we need to add the delimiters if they are missing
# The config will be re-added afterwards
if ! grep -q "begin ${app}" /root/.ssh/config; then
    # did not find delimiters so removing old configuration
    sed -e "/Host ${server}/,+6d" "/root/.ssh/config" -i || true
fi

#=================================================
# INSTALL RESTIC
#=================================================
ynh_script_progression --message="Installing Restic..." --weight=7

ynh_setup_source --source_id=main --dest_dir="$install_dir"
chmod +x "$install_dir/restic"

# This function will only create it if required
_gen_and_save_public_key

# Set ssh config if it is missing
if ! grep -q "begin $app" "/root/.ssh/config"; then
    _set_ssh_config
fi

#=================================================
# SETUP THE BACKUP METHOD
#=================================================
ynh_script_progression --message="Setting up backup method..." --weight=1

mkdir -p /etc/yunohost/hooks.d/backup
mkdir -p /etc/yunohost/hooks.d/backup_method
mkdir -p /usr/share/yunohost/backup_method

## Backup method
_ynh_add_config_j2 --template="backup_method.j2" --destination="/etc/yunohost/hooks.d/backup_method/05-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/05-${app}_app"

_ynh_add_config_j2 --template="backup-with-restic.j2" --destination="$install_dir/backup-with-restic"
chmod u+x "$install_dir/backup-with-restic"

## Check method
_ynh_add_config_j2 --template="check_method.j2" --destination="$install_dir/check_method_restic"

_ynh_add_config_j2 --template="check-restic.j2" --destination="$install_dir/check-restic"
chmod u+x "$install_dir/check-restic"

## Backup log script
_ynh_add_config_j2 --template="restic_log.j2" --destination="$install_dir/restic_log"
chmod u+x "$install_dir/restic_log"

# Check log script
_ynh_add_config_j2 --template="restic_check_log.j2" --destination="$install_dir/restic_check_log"
chmod u+x "$install_dir/restic_check_log"

chown -R "$app:$app" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Systemd services and timers
for suffix in "${systemd_services_suffixes[@]}"; do
    ynh_add_systemd_config --service="$app$suffix" --template="systemd$suffix.service"
    _ynh_add_config_j2 --template="systemd$suffix.timer.j2" --destination="/etc/systemd/system/$app$suffix.timer"
    ynh_systemd_action --service_name="${app}$suffix.service" --action="disable"
    systemctl enable --quiet "${app}$suffix.timer"
    ynh_systemd_action --service_name="${app}$suffix.timer" --action="start"

    yunohost service add "$app$suffix" --description="Restic backup program ($app$suffix)" \
        --test_status="systemctl show $app$suffix.service  -p ActiveState --value | grep -v failed"
done

ynh_add_config --template="sudoer" --destination="/etc/sudoers.d/$app"
chown root:root "/etc/sudoers.d/$app"

ynh_use_logrotate --logfile="/var/log/restic_backup_${app}.log"
ynh_use_logrotate --logfile="/var/log/restic_backup_${app}.err"
ynh_use_logrotate --logfile="/var/log/restic_check_${app}.log"
ynh_use_logrotate --logfile="/var/log/restic_check_${app}.err"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed"
